name: ntpsec
version: 1.0
summary: The NTP reference implementation, refactored
description: |
  The NTP reference implementation, refactored.

grade: devel 
confinement: strict

apps:
  ntpd:
    command: usr/local/sbin/ntpd -c $SNAP/ntp.conf -n
    daemon: simple
    plugs: [system-trace, process-control, time-control, network, network-bind, network-observe]
  ntpq:
    command: usr/local/bin/ntpq
    plugs: [network]
  ntpfrob:
    command: usr/local/bin/ntpfrob
    plugs: [network]
  ntpleapfetch:
    command: usr/local/bin/ntpleapfetch
    plugs: [network]
  ntptime:
    command: usr/local/bin/ntptime
    plugs: [network]
  ntpviz:
    command: usr/local/bin/ntpviz
    plugs: [network]
  ntpdig:
    command: usr/local/bin/ntpdig
    plugs: [network]
  ntpkeygen:
    command: usr/local/bin/ntpkeygen
    plugs: [network]
  ntpmon:
    command: usr/local/bin/ntpmon
    plugs: [network]
  ntpsweep:
    command: usr/local/bin/ntpsweep
    plugs: [network]
  ntptrace:
    command: usr/local/bin/ntptrace
    plugs: [network]
  ntpwait:
    command: usr/local/bin/ntpwait
    plugs: [network]

parts:
  ntpsec:
    plugin: waf
    source: https://gitlab.com/NTPsec/ntpsec.git
    source-type: git
    configflags:
      - --enable-leap-smear
    build-packages: [libcrypto++-dev, libcap-dev, python-ntplib]
    stage-packages: [python]
    install: |
      cat ../build/contrib/ntp.conf.basic.sample > $SNAPCRAFT_PART_INSTALL/ntp.conf
      echo rlimit memlock -1 >> $SNAPCRAFT_PART_INSTALL/ntp.conf

