name: ntpsec
version: 0.9.6
summary: The NTP reference implementation, refactored
description: |
  The NTP reference implementation, refactored.

grade: devel 
confinement: classic

apps:
  ntpd:
    command: usr/local/sbin/ntpd -c $SNAP/etc/ntp-conf.d/example.conf -u 123
    daemon: forking
    plugs: [time-control, network, network-bind]
  ntpq:
    command: usr/local/bin/ntpq
    plugs: [network]
  ntpfrob:
    command: usr/local/bin/ntpfrob
    plugs: [network]
  ntpleapfetch:
    command: usr/local/bin/ntpleapfetch
    plugs: [network]
  ntptime:
    command: usr/local/bin/ntptime
    plugs: [network]
  ntpviz:
    command: usr/local/bin/ntpviz
    plugs: [network]
  ntpdig:
    command: usr/local/bin/ntpdig
    plugs: [network]
  ntpkeygen:
    command: usr/local/bin/ntpkeygen
    plugs: [network]
  ntpmon:
    command: usr/local/bin/ntpmon
    plugs: [network]
  ntpsweep:
    command: usr/local/bin/ntpsweep
    plugs: [network]
  ntptrace:
    command: usr/local/bin/ntptrace
    plugs: [network]
  ntpwait:
    command: usr/local/bin/ntpwait
    plugs: [network]

parts:
  ntpsec:
    plugin: waf
    source: https://gitlab.com/NTPsec/ntpsec.git
    source-type: git
    configflags:
      - --enable-leap-smear
    build-packages: [libcrypto++-dev, libcap-dev, python-ntplib]
    stage-packages: [python, libpython2.7]
    organize:
      ../build/etc/ntp-conf.d: etc/ntp-conf.d
